### ISSUE TITLE
Продлить время логина

### ISSUE THREAD

**Issue by enrey** [IT3G/work-calendar#106]
**Проблема:**
Приходится логиниться в систему по 10 раз на дню, т.к. постоянно выкидывает "по таймауту".

**Цель:**
Сделать возможность постоянно не перелогиниваться.

**Реализовать:**
Можно сделать доп.галку при логине "запомнить" - как сделано в большинстве систем - Jira, Confluence и т.д. Или ваши варианты.

**Comment by klimentru1986** [comment]
Нужно добавить refresh token
