### ISSUE TITLE
Прекомит хуки для форматирования

### ISSUE THREAD

**Issue by klimentru1986** [IT3G/work-calendar#109]
**Цель:**
Унифицировать форматирование.

**Реализовать:**
Сделать прекомит хуки с husky, lint-staged и prettier

**Comment by urdenko** [comment]
Не получается быстро сделать так, что бы работало одновременно на backend и fronted папках. Возможно потребуется объединить package.json в один корневой

**Comment by enrey** [comment]
Я добавил во frontend-папку, оно автоматом заработало и на бекенд папке.
Поживём-посмотрим как оно будет работать, пока полет нормальный.
