### ISSUE TITLE
"Моё" и "не моё" присутствие

### ISSUE THREAD

**Issue by enrey** [IT3G/work-calendar#140]
**Проблема:**
В хедере есть ссылка "Мое присутствие".
Если открыть страницу "Присутствие" другого человека - то эта ссылка останется "активной", хотя будет вести на другой урл.

**Реализовать:**
1. Если открыто "Присутствие" другого человека - не отображать в хедере ссылку "Мое присутствие" как уже выбранную.
2. Аналогичная проблема с пунктом "Профиль", ее тоже исправить. Можно даже переименовать в "Мой профиль" для ясности.

**Comment by klimentru1986** [comment]
Надо подождать заливку рестайлинга шапки.
