### ISSUE TITLE
В окне проектов не отображаются сотрудники, город которых не совпадает с одним из офисов.

### ISSUE THREAD

**Issue by Souverain73** [IT3G/work-calendar#176]
Есть сотрудники на удаленке. В профиле указывают город проживания. 
Так как город не совпадает ни с 1-м из офисов в просмотре проектов сотрудник не отображается.
![изображение](https://user-images.githubusercontent.com/21988201/78239695-b834f580-74e6-11ea-95ed-4c70973beca0.png)
![изображение](https://user-images.githubusercontent.com/21988201/78239737-c4b94e00-74e6-11ea-9c89-f6fc68aeec66.png)

В результате количество человек в шапке не соответствует количеству отображаемых сотрудников.

Предлагаю добавить колонку "Остальные" или "Удаленные сотрудники" для отображения таких людей.

**Comment by enrey** [comment]
Связано с #142

**Comment by klimentru1986** [comment]
Сделано в рамках страницы "Люди"
