### ISSUE TITLE
Окрас праздничного и предпразничного дня в календаре

### ISSUE THREAD

**Issue by Bwca** [IT3G/work-calendar#185]
Цвета используемые для окраса плиток предпразничных и праздничных дней на странице присутствия визуально достаточно похожи:
background-color: rgb(239, 236, 236);
background-color: rgba(197, 202, 233, 0.4);

**Фактический результат:**
Предпразничные/праздничные дни почти сливаются, их тяжело отличить друг от друга.

**Желаемый результат:**
Предпразничные/праздничные дни имею более легко отличимые цвета и не сливаются.

**Comment by klimentru1986** [comment]
Welcome to PR )
