### ISSUE TITLE
Неверная "дата последнего посещения"

### ISSUE THREAD

**Issue by enrey** [IT3G/work-calendar#226]
**Текущее поведение:**

В карточке сотрудника отображается некорректная полу-рандомная дата последнего захода в календарь.
![image](https://user-images.githubusercontent.com/37715267/122550500-67061880-d03c-11eb-8373-d71a8f7400ce.png)

**Ожидаемое поведение:**
В карточке сотрудника отображается корректная дата-время, когда каждый пользователь последний раз посещал календарь.

**Comment by klimentru1986** [comment]
Поправлено в рамках https://github.com/IT3G/work-calendar/pull/228
