### ISSUE TITLE
Реализовать настраиваемый механизм подписок

### ISSUE THREAD

**Issue by enrey** [IT3G/work-calendar#81]
1. В профиле каждого пользователя появляются два блока "я подписан на" и "на меня подписаны".

2. Рассчет "кто/кого уведомляем" переезжает на server-side и становится "полу-автоматическим":
- часть пользователей вычисляется автоматически в момент отправки уведомления, часть пользователей может добавляться вручную (подписаться, отписаться)
- добавленные вручную имеют приоритет над автоматическим алгоритмом (пересечение) и хранятся в Mongo.

3. Админ может дополнительно подписывать/отписывать людей по обоим спискам для всех пользователей.

4. Также должны поддерживаться следующие сценарии использования:

4.1. Если у человека не задан проект, то:
- он получает уведомления от всех (если от кого-то почему-то не хочет - то может отписаться в своем профиле)
- от него по умолчанию никто не получает уведомления (только если специально подписаться, либо подпишет админ). 

4.2. Если человеку проставил изменение присутствия кто-то другой, то этому человеку наравне с остальными также дополнительно приходит данное уведомление .

**Comment by AVoits** [comment]
Реализовано в 
https://github.com/enrey/work-calendar/pull/82
