### ISSUE TITLE
Фильтр "команда" со значением по умолчанию

### ISSUE THREAD

**Issue by enrey** [IT3G/work-calendar#97]
**Проблема:**
Неудобно смотреть кто из текущей команды в отпуске, болеет и т.д.

**Цель:**
Сделать удобней, сократить количество кликов.

**Реализовать:**
Фильтр "Проект" по умолчанию при переходе в "Команда" - выставлять в текущий проект пользователя (с максимальным %).
Добавить крестик для быстрой очистки фильтра.

![image](https://user-images.githubusercontent.com/37715267/74433815-31fb1c00-4e72-11ea-9ef9-981407717ffa.png)

**Comment by klimentru1986** [comment]
Возможно стоит сделать мультиселект, для тех у кого несколько проектов.
