### ISSUE TITLE
Доработать вкладку "Проекты"

### ISSUE THREAD

**Issue by enrey** [IT3G/work-calendar#99]
**Проблема:**
Вкладка недостаточно информативна.

**Цель:**
Сделать удобней, убрать ненужную информацию.

**Реализовать:**
На странице "Проекты":
1. Не выводить проекты у которых нет людей (пустые).
2. Вывести поле "Позиция" рядом с человеком как-нибудь "красивенько" - для понимания - разработчик, QA, аналитик и т.д.
3. Добавить фильтр "Подразделение" по аналогии как на странице "Команда" - это позволит просматривать "только разработчиков", "только манагеров" и т.д.

**Comment by AVoits** [comment]
#133
